### ISSUE TITLE
Dataset + models on another platform than Baidu

### ISSUE THREAD

**Issue by iraadit** [QiaoLiuHit/MMNet#2]
Would it be possible to put the dataset and models on another website/platform than Baidu?

I'm in Europe (Belgium) and unable to download on Baidu.

Thank you

**Comment by QiaoLiuHit** [comment]
> Would it be possible to put the dataset and models on another website/platform than Baidu?
> 
> I'm in Europe (Belgium) and unable to download on Baidu.
> 
> Thank you

Now you can download the dataset from [MEGA drive](https://mega.nz/#F!BtAVyAwb!hRsl9pCKp5JmJur_UHpEwA)  and  I have updated  'readme', you can download the modles and tracking raw results from there.

**Comment by iraadit** [comment]
Thank you!
