### ISSUE TITLE
mat数据请求

### ISSUE THREAD

**Issue by huozhe05** [QiaoLiuHit/MMNet#4]
可以给一份TIRDataset-MMNet-stats.mat和imdb_TIRvideo-MMNet.mat数据嘛！我用ILSVRC15-curation跑出来的mat数据无法在该代码上训练，不清楚mat是否有问题。麻烦了！

**Comment by huozhe05** [comment]
就会出现这样的错误：无法执行赋值，因为左侧的大小为 255×255×3，右侧的大小为 255×255×9。在imout_z(:,:,:,i) = repmat((tmp_z/255)*255, [1 1 3]);处

**Comment by QiaoLiuHit** [comment]
> 可以给一份TIRDataset-MMNet-stats.mat和imdb_TIRvideo-MMNet.mat数据嘛！我用ILSVRC15-curation跑出来的mat数据无法在该代码上训练，不清楚mat是否有问题。麻烦了！

这两份.mat数据是通过在我们提出的热红外数据集制作训练样本时候产生的，制作训练样本的过程与CFNet中相同。我提供的.mat数据可能并不适合你的环境，需要你自己制作产生。
