### ISSUE TITLE
results on LSOTB-TIR

### ISSUE THREAD

**Issue by xjtuwh** [QiaoLiuHit/MMNet#5]
Hello~ I'm interested in this work and I want to compare it with my algorithms on LSOTB-TIR dataset. Can you give me the results on  LSOTB-TIR dataset?

**Comment by QiaoLiuHit** [comment]
> Hello~ I'm interested in this work and I want to compare it with my algorithms on LSOTB-TIR dataset. Can you give me the results on LSOTB-TIR dataset?

You can download the result in [here](https://pan.baidu.com/s/1D88Rg-NspfzHRg4nE8C7Lw?pwd=o9ll)

**Comment by xjtuwh** [comment]
Thank you very much.
